# Generated by Django 3.0.5 on 2020-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('did', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sender', models.BigIntegerField()),
                ('reciever', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField(unique_for_date=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
