# Generated by Django 3.0.5 on 2020-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={},
        ),
        migrations.AlterField(
            model_name='dialogs',
            name='reciever',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dialogs',
            name='sender',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
