# Generated by Django 3.0.5 on 2020-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0002_auto_20200510_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogs',
            name='did',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
