# Generated by Django 3.0.5 on 2020-05-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0003_auto_20200510_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
