# Generated by Django 3.0.5 on 2020-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0004_messages_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='None', max_length=65, unique=True),
        ),
    ]
