# Generated by Django 3.0.5 on 2020-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0007_auto_20200528_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=25),
        ),
    ]
