# Generated by Django 3.0.5 on 2020-05-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projsite', '0009_auto_20200528_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
